/** 设置页的全部文字（目前只有中文；加英文就补一份同结构的表）。 */
import { COMPAT_LABEL } from "../shared.js";
export const zh = {
    sectionLabel: '局域网web访问',
    title: '局域网web访问',
    hero: {
        switchLabel: '启用插件（关闭后恢复 dsh 官方的登录方式）',
        running: '正在运行',
        localOnly: '仅本机和 SSH 隧道',
        lanOpen: '局域网已开放',
        loggedIn: (n) => `${n} 个浏览器已登录`,
        disabled: '已停用 · 现在用 dsh 官方的 token 方式登录',
        loading: '正在读取状态…',
        unreachable: '读不到插件状态，请刷新重试',
        /** 总开关关着时，分组下方的说明（设计稿「插件已停用」）。 */
        keptWhileOff: '下面的设置都保留着，打开总开关后原样恢复。',
        /** 运行检查没通过、已安全退出。 */
        fault: '已暂停 · 已退回 dsh 官方登录方式',
        checking: '正在做运行检查…',
    },
    /** 安全退出时状态头下方的红条：标题写第一项没通过的，正文说影响和怎么办。 */
    fault: {
        title: {
            webServer: '没能接入 dsh 的网页服务',
            signing: '读不到 dsh 的登录签名',
            sessionKey: '局域网登录密钥没准备好',
            dshVersion: 'dsh 版本超出插件支持的范围',
        },
        body: '免 token 和局域网入口已关闭，Desktop 不受影响。等插件更新后到「关于」点「重新检查」。',
        more: '查看运行检查',
    },
    tabs: {
        aria: '设置分类',
        conn: '连接',
        dev: '设备',
        sec: '安全',
        about: '关于',
    },
    conn: {
        localLabel: '本机免登录',
        localDesc: '在这台电脑或经 SSH 隧道打开时直接进入，不用 token',
        copyLocal: '复制本机访问地址',
        copied: '已复制本机访问地址',
        copyFailed: '没能复制，请手动选中地址复制',
        /** 没设密码时去关「本机免登录」的提示。 */
        needPassword: '先在「安全」里设置管理密码',
        lanLabel: '局域网访问',
        lanDesc: '同一网络里的其他设备用浏览器打开，需要密码',
        lanPortInUse: (port) => `没能打开：端口 ${port} 被别的程序占用了，换一个端口再试`,
        lanHostUnavailable: '没能打开：选中的网卡现在不在这台电脑上，换一块网卡再试',
        lanGroup: '局域网入口',
        firewallTitle: '系统可能会弹窗询问',
        firewallBody: '如果系统询问是否允许 dsh 接受连接，请点「允许」，否则其他设备连不上。',
        addrLabel: '访问地址',
        copyLan: '复制访问地址',
        copiedLan: '已复制访问地址',
        nicLabel: '监听网卡',
        nicDesc: '选「所有网卡」时，Wi-Fi、有线、Tailscale 都能连进来',
        nicAll: '所有网卡',
        /** 100.64.0.0/10 网段的网卡（Tailscale 这类异地组网）。 */
        nicOverlay: '组网',
        nicMissing: '选中的网卡现在不在这台电脑上（断网或组网软件已退出），换一块网卡',
        nicNoNetwork: '没有检测到可用网络',
        portLabel: '端口',
        portDesc: '改完按回车生效，不用重启',
        portSaved: '已保存，局域网入口已在新端口重开',
        portInvalid: '端口要在 1 到 65535 之间',
        portIsMain: (port) => `${port} 是 dsh 自己的端口，换一个`,
        portInUse: (port) => `端口 ${port} 被别的程序占用了，换一个端口再试`,
        insecure: '局域网连接没有加密，同一网络里的人可能截到密码。只在家里、公司内网或 Tailscale 这类组网里打开。',
    },
    dev: {
        groupTitle: '允许的设备',
        signOutAll: '全部退出登录',
        signedOutAll: '所有浏览器已退出登录',
        loggedIn: '已登录',
        notLoggedIn: '未登录',
        manyLoggedIn: (n) => `${n} 个浏览器已登录`,
        bypass: '免密码',
        neverSeen: '还没来访过',
        active: (ago) => `${ago}活跃`,
        add: '添加设备…',
        addShort: '添加设备',
        foot: '不在列表里的设备，连登录页都打不开。点一行可以让它退出登录，或把它移出列表。',
        emptyText: '还没有允许的设备。加进来的设备才能打开登录页。',
        emptyFoot: (mode) => `列表为空时：${mode}。`,
        emptyModeLabel: '列表为空时',
        emptyMode: { 'deny-all': '拒绝所有设备', 'private-only': '允许所有私有网段' },
        bypassLabel: '列表里的设备免密码',
        bypassDesc: '同一网络里的人可以冒用 IP，只在完全可信的网络里打开',
        othersTitle: '其他已登录的浏览器',
        othersDesc: '不在允许列表里，是「列表为空时允许所有私有网段」放进来的',
        detailLead: '允许这台设备打开登录页。',
        nameLabel: '名称',
        namePlaceholder: '例如：客厅的 iPad',
        valueLabel: 'IP 或网段',
        valuePlaceholder: '192.168.1.23',
        loginState: '登录状态',
        signOut: '退出登录',
        signedOut: (who) => `${who} 已退出登录`,
        /** 退出登录提示里「谁的哪个浏览器」。 */
        whoBrowser: (who, browser) => `${who} 的 ${browser}`,
        loadFailed: '没能读到设备列表',
        retry: '重试',
        signOutNote: '退出登录后，它下次打开要重新输入密码；设备仍在允许列表里。',
        bypassNote: '开着「列表里的设备免密码」，这台设备不用登录，没有可退出的登录。',
        noSessions: '现在没有登录着的浏览器。',
        loginSince: (date) => `${date}登录`,
        remove: '移出列表',
        removed: (name) => `已把 ${name} 移出列表，它的登录也已失效`,
        cancel: '取消',
        done: '完成',
        addTitle: '添加设备',
        addLead: '加进来的设备才能打开登录页，登录仍需要密码。',
        addLeadBypass: '加进来的设备开着免密码时直接进入，不用输密码。',
        addConfirm: '添加',
        added: (name) => `已添加 ${name}`,
        valueHint: '一台设备填 IP，如 192.168.1.23；一整个网段填 192.168.1.0/24',
        valueSingle: '单台设备',
        valueRange: '网段：这一段里的所有设备都允许',
        valueInvalid: '格式不对：应为 192.168.1.23 或 192.168.1.0/24',
        valueDuplicate: '这个地址已经在列表里了',
        recentTitle: '最近被拒绝的地址，点一下填入',
        recentMeta: (count, when) => `${count} 次 · ${when}`,
        date: (d) => `${d.getMonth() + 1} 月 ${d.getDate()} 日`,
    },
    sec: {
        groupPassword: '密码与登录',
        passwordLabel: '管理密码',
        passwordSet: (ago) => `已设置 · ${ago}修改`,
        passwordSetNoTime: '已设置',
        passwordUnset: '未设置',
        change: '更改',
        newPassword: '新密码',
        showPassword: '显示密码',
        cancel: '取消',
        save: '保存',
        setFirst: '设置',
        hint: '至少 12 位，保存后所有已登录的设备都要重新登录',
        hintFirst: '至少 12 位，设好后才能打开局域网访问',
        short: (n) => `还差 ${n} 位`,
        enough: '长度够了',
        changed: '密码已更新，其他设备需要重新登录',
        setDone: '管理密码已设置',
        keepLabel: '登录保持',
        keepDesc: '过期后要重新输入密码',
        days: (n) => `${n} 天`,
        clear: '清除密码…',
        clearTitle: '清除管理密码？',
        clearBody: '清除后会同时：关闭局域网访问、让所有局域网设备退出登录。本机和 SSH 隧道不受影响。之后要用局域网，需要重新设置密码。',
        clearReopenLocal: '同时会重新打开「本机免登录」，否则浏览器将无法进入。',
        clearConfirm: '清除密码',
        cleared: '密码已清除，局域网访问已关闭',
        groupLog: '访问记录',
        logAll: (n) => `全部 ${n} 条`,
        logTitle: '访问记录',
        logFoot: '只保存最近 200 条；dsh 重启后清空。',
        logEmpty: '还没有记录。局域网设备登录、被拒绝时会记在这里。',
        logLoadFailed: '没能读到访问记录，稍后会自动再试',
        times: (n) => `${n} 次`,
        filterAria: '筛选',
        filter: { all: '全部', deny: '拒绝', login: '登录' },
        done: '完成',
        kind: {
            'whitelist-deny': '不在列表里，已拒绝',
            unauthorized: '没登录，已拒绝',
            'cross-site': '别的网站发来的请求，已拒绝',
            'login-failed': '密码错误',
            login: '登录成功',
            logout: '退出登录',
            kick: '被踢下线',
            removed: '移出列表',
            update: '插件更新',
            'selfcheck-fail': '运行检查没通过',
        },
        today: '今天',
        yesterday: '昨天',
    },
    about: {
        groupVersion: '版本',
        plugin: '插件',
        dsh: 'dsh',
        runtime: '运行环境',
        edition: { desktop: 'Desktop', web: 'Web', unknown: '未知' },
        port: (p) => `主端口 ${p}`,
        unknownVersion: '未知',
        dshInRange: (v) => `${v} · 在支持范围内`,
        dshOutOfRange: (v) => `${v} · 超出支持范围`,
        update: {
            checking: '正在查询最新版本',
            latest: (v) => `${v} 是最新版本`,
            available: (cur, next) => [`当前 ${cur} · `, `有新版本 ${next}`],
            unavailable: (cur) => `当前 ${cur} · 暂时查不到新版本`,
            running: '大约需要 30 秒，别关 dsh',
            done: (v) => `已更新到 ${v}，重启 dsh 后生效`,
            failed: {
                network: '连不上更新服务器。检查网络后重试，设置不受影响',
                'no-command': (cmd) => `找不到 dsh 命令，设置不受影响。可以在终端运行：${cmd}`,
                failed: '更新没成功，设置不受影响。可以重试',
            },
            check: '检查更新',
            to: (v) => `更新到 ${v}`,
            busy: '更新中…',
            retry: '重试',
            dot: '有新版本',
        },
        groupChecks: '运行检查',
        allPassed: (n) => `· ${n} 项全部通过`,
        passedSomeUnset: (ok, idle) => `· ${ok} 项通过 · ${idle} 项未设置`,
        someFailed: (n) => `· ${n} 项没通过`,
        pending: '· 正在检查',
        recheck: '重新检查',
        rechecking: '检查中…',
        toastPassed: (n) => `${n} 项检查全部通过`,
        toastPassedUnset: (ok) => `${ok} 项检查通过，管理密码未设置`,
        toastFailed: (n) => `有 ${n} 项没通过`,
        checksFoot: '前四项任何一项不通过，插件会自动退回 dsh 官方的登录方式并关闭局域网入口，这里会写明原因。',
        check: {
            webServer: {
                label: '接入 dsh 网页服务',
                ok: (port) => `插件已挂到 dsh 的网页服务上，主端口 ${port}`,
                bad: '没能挂到 dsh 的网页服务上',
            },
            signing: {
                label: '读取 dsh 登录签名',
                ok: '能读到 dsh 的签名密钥，所以本机和 SSH 隧道可以免 token 进入',
                bad: '读不到 dsh 的签名密钥，dsh 升级后格式可能变了',
            },
            sessionKey: {
                label: '局域网登录密钥',
                ok: '已生成，局域网设备登录后能保持登录',
                bad: '没能生成，局域网设备登录后保持不住',
            },
            dshVersion: {
                label: 'dsh 版本',
                ok: (v) => `${v}，在插件支持的 ${COMPAT_LABEL} 之内`,
                unknown: '读不到 dsh 的版本号，按支持处理',
                warn: (v) => `${v}，超出插件支持的 ${COMPAT_LABEL}`,
            },
            password: {
                label: '管理密码',
                ok: '已设置，局域网访问可以打开',
                idle: '未设置，设好后才能打开局域网访问',
            },
        },
        stateLabel: { ok: '通过', bad: '没通过', warn: '需要注意', idle: '未设置' },
    },
    readOnly: {
        title: '只能查看',
        thisDevice: '这台设备',
        body: (ip, machine) => `你正在从 ${ip} 访问。要修改设置，请在 ${machine} 本机或通过 SSH 隧道打开。`,
        /** 取不到电脑名时的说法。 */
        thisMachine: '装 dsh 的电脑',
        on: '开',
        off: '关',
    },
    time: {
        justNow: '刚刚',
        minutes: (n) => `${n} 分钟前`,
        hours: (n) => `${n} 小时前`,
        days: (n) => `${n} 天前`,
    },
    undo: '撤销',
    errors: {
        /** 请求根本没送到（网络断了、dsh 没在跑）。 */
        noResponse: '没能保存，dsh 没有响应，稍后再试',
        /** dsh 收到了但拒绝了，又没有更具体的原因。 */
        rejected: '没能保存，请刷新页面后再试',
        localOnly: '只能在装 dsh 的电脑本机上修改',
        /** 保存成功后重新读取状态失败（页面保留原来的内容）。 */
        refreshFailed: '已保存，但没能刷新状态，请稍后刷新页面',
        /** 定时刷新读不到状态（dsh 停了、断网）：只提示一次，恢复后不再提示。 */
        pollFailed: '连不上 dsh，页面上显示的可能不是最新的',
        /** 允许列表的条目不合法、或已经有这个地址。 */
        invalidSetting: '这个值 dsh 不接受，检查一下再试',
        duplicate: '列表里已经有这个地址了',
    },
};
